### ISSUE TITLE
师傅您好

### ISSUE THREAD

**Issue by 98Kstar** [smxiazi/xp_CAPTCHA#1]
师傅您好，这个现在接那个打码平台我按照您的那个用户名密码写进去 报用户名密码错误，是否已经平台更改了接口

**Comment by smxiazi** [comment]
已修改，请重新试试。

**Comment by 98Kstar** [comment]
感谢师傅，您这个修改后跟您那个白嫖的还是继续兼容的吧？

**Comment by smxiazi** [comment]
两个单独的程序，一个是调用别人的接口（更加准确），一个是本地的服务，无论改哪个都不会有冲突。

**Comment by 98Kstar** [comment]
谢谢师傅
