### ISSUE TITLE
无法加载 报错

### ISSUE THREAD

**Issue by guchangan1** [smxiazi/xp_CAPTCHA#2]
![image](https://user-images.githubusercontent.com/54949079/132021015-7edc05ec-0a21-44e6-b1ee-14f6c611a638.png)

**Comment by smxiazi** [comment]
需要jython版本大于等于2.7.1

**Comment by smxiazi** [comment]
![image](https://user-images.githubusercontent.com/30351807/132076822-70f8805b-685f-44be-b183-a442f7cb642e.png)

**Comment by guchangan1** [comment]
> 需要jython版本大于等于2.7.1

确实是2.7.2
![image](https://user-images.githubusercontent.com/54949079/132090714-674508fd-dac8-4599-8ee3-044c472d7c7b.png)

**Comment by ChuTian-CN** [comment]
应该是GBK编码的问题吧
