### ISSUE TITLE
无法正常加载

### ISSUE THREAD

**Issue by sunian19** [smxiazi/xp_CAPTCHA#4]
瞎子哥，我也是这个问题。
burp换成gbk编码也不行
使用jython-standalone-2.7.1.jar
![image](https://user-images.githubusercontent.com/53205380/153154638-5cb065fd-544c-4e61-b15a-7fbaf6a10b12.png)

**Comment by smxiazi** [comment]
把脚本的第二行换成
#coding:utf-8
