### ISSUE TITLE
希望作者可以将API接口信息，放到配置文件或者python文件中做验证，否则，容易泄漏自己的账号信息。

### ISSUE THREAD

**Issue by V0WKeep3r** [smxiazi/xp_CAPTCHA#5]
希望作者可以将API接口信息，放到配置文件或者python文件中做验证，否则，容易泄漏自己的账号信息。

事实上，我也会在fork之后进行修改。目前的执行逻辑需要在爆破过程中，放上一个xiapao的header，**会泄漏自己的API接口的账号密码**。目前我的思路是，账号密码配置，放到一个同目录的配置文件或者静态写入python执行文件中，然后xiapao的header只存放验证码生成地址。

希望作者参考。

**Comment by smxiazi** [comment]
已跟新，代码现在马上发布
